[package]
name = "smol-rs"
version = "0.1.0"
authors = ["nich0s"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.1"
sqlite = "0.25.0"
rand = "0.7.3"